### PR TITLE
Specify the correct uriParameter values for the custom object resource

### PR DESCRIPTION
**Pull request by mvantellingen**
For code generation we need to signal that the path takes two parameters (conatiner and key)

### CODE REVIEW

**Comment by jenschude** [comment]
Could you please enable "Allow edits from maintainer" so I could push to your branch.

**Comment by mvantellingen** [comment]
That option doesn't seem to be available if the origin branch is from an organization

**Comment by jenschude** [comment]
Okay than I will open a new PR with the changes 😁

**Comment by jenschude** [comment]
Okay than I will open a new PR with the changes 😁

**Comment by jenschude** [comment]
See #161

**Pull request closed without merging**
