### PR TITLE
Add missing detailedErrorMessage on InvalidJsonInputError

### PR DESCRIPTION
**Pull request by mvantellingen**
Adding the detailedErrorMessage allows us to expose more info on auto-generated api's

### CODE REVIEW

**Comment by jenschude** [comment]
Thanks for your contribution 👍

**Comment by jenschude** [comment]
Ah sorry. I had to revert this PR. The issue is, that this field is not officially documented, so one should not rely on the existance of this field. As long as it's not documented I can't merge this.

**Comment by wrsenn** [comment]
Is there any reason this isn't officially documented? This is relatively crippling to generated SDKs like this since it leaves the user with no meaningful feedback.

**Comment by katmatt** [comment]
We have some properties in our API JSON payload that aren’t documented. If we find such properties, we normally start a discussion with our backend teams about these properties and then they decide if these properties should be added to our docs. Only then we can add them in our api-spec and only then we can add them to our generated SDKs…

**Comment by katmatt** [comment]
@wrsenn If such a field isn't documented, then it's neither in a manually generated nor a auto-generated SDK. That means that both are at least consistent with our docs.

**Comment by kurtlippert** [comment]
To Rob's question though, why *isn't* this documented? Shouldn't (ideally) all aspects of the API that are available be documented?

**Pull request merged**
